### ISSUE TITLE
noIcons not working

### ISSUE THREAD

**Issue by emersonbottero** [jifalops/iron-collapse-button#2]
when I use <iron-collapse-button opened> it works  (the content is show)
when I use <iron-collapse-button noIcons> the expanded/Collapse icons still shows.

just try using it in the PSK.

**Comment by emersonbottero** [comment]
`<app-drawer id="drawer" slot="drawer">
        <app-toolbar>Menu</app-toolbar>
          <iron-collapse-button noIcons>
            <paper-button class="menu" slot="collapse-trigger">Organização de Dados</paper-button>
            <div slot="collapse-content">
              <iron-selector selected="[[page]]" attr-for-selected="name" class="drawer-list" role="navigation">
                <a name="view1" href="view1">Arquivos</a>
                <a name="view2" href="view2">Códigos</a>
                <a name="view3" href="view3">Modelos 3D</a>
              </iron-selector>
            </div>
          </iron-collapse-button>
      </app-drawer>`

**Comment by jifalops** [comment]
no-icons in html

**Comment by emersonbottero** [comment]
it Worked, my bad.
thanks
