### ISSUE TITLE
won't expand in iron-list

### ISSUE THREAD

**Issue by ratracegrad** [jifalops/iron-collapse-button#4]
I am using your item to populate values for title and content areas from an iron-list that is within an iron-scroll-threshold. When I click on an item to expand it, it expands but the item below it does not move down so the content area spills out over the title of the items below it.  If I remove the iron-list and manually fill in title and content it works. Any suggestion on how to get it working within an iron-list in an iron-scroll-threshold?

**Comment by jifalops** [comment]
See [issue 158](https://github.com/PolymerElements/iron-list/issues/158) (and related) with iron-list. Each item in an iron-list creates its own stacking context. There are workarounds but I'm not aware of an official solution yet.
